$(function(){
    $("#bisihuirb").click(function(){
        $(".xiadasang").toggle();
        $("#bisihuirb").css("background-color","#CCD6B3");
    });
});
$(function(){
    $("#shiwuenjue").click(function(){
        $(".shoquti").toggle();
    });
});
$(function(){
    $(".gendguo").click(function(){
        $(".tiaojismssdsia").toggle();
    });
});
$(function(){
    $(".gendguoweq").click(function(){
        $(".tiaojismsa").toggle();
    });
});
/*
/!*选择职业类别*!/
$(function(){
    $(".xuashueh ul li").click(function(){
        $(".sanjistanchaung").toggle();
    });
});*/
